server:
  port: 8888
  servlet:
    context-path: /myblog
spring:
  application:
    name: myblog
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    port: 6379
    connect-timeout: 5000

  # 七牛云配置
  servlet:
    multipart:
      # 单个文件最大值
      max-file-size: 2MB
      # 上传文件最大值
      max-request-size: 20MB


#mybatis
mybatis:
  configuration:
    #开启驼峰命名转换
    map-underscore-to-camel-case: true
  type-aliases-package: com.hwh.common.domain